seq_len: 625
depth: 8
latent_dim: 32
base_kernels: 32
lr: 0.01
weight_decay: 1.0e-05
lr_patience: 5
lr_factor: 0.5
use_scheduler: true
_instantiator: lightning.pytorch.cli.instantiate_module
csv_path: data/train.csv
data_dir: data/train
batch_size: 256
num_workers: 4
pin_memory: true
val_size: 0.1
test_size: 0.1
random_state: 42
